# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Partially Separable Function Optimization
#'
#' @description
#' Optimization for specially structured partially separable function.
#' See \code{vignette("psqn", package = "psqn")} for details.
#'
#' @param par Initial values for the parameters.
#' @param fn Function to compute the element functions and their
#' derivatives.
#' @param n_ele_func Number of element functions.
#' @param rel_eps Relative convergence threshold.
#' @param n_threads Number of threads to use.
#' @param max_it Maximum number of iterations.
#' @param cg_rel_eps Relative convergence threshold for conjugate gradient method.
#' @param c1,c2 Tresholds for the Wolfe condition.
#' @param use_bfgs Logical for whether to use BFGS updates or SR1 updates.
#'
#' @export
psqn <- function(par, fn, n_ele_func, rel_eps = .00000001, max_it = 100L, n_threads = 1L, cg_rel_eps = .001, c1 = .0001, c2 = .9, use_bfgs = TRUE) {
    .Call(`_psqn_psqn`, par, fn, n_ele_func, rel_eps, max_it, n_threads, cg_rel_eps, c1, c2, use_bfgs)
}

